### ISSUE TITLE
how to ack a message

### ISSUE THREAD

**Issue by stephanMettler** [easternbloc/node-stomp-client#23]
how to ack?

**Comment by gknapp** [comment]
I wrote some `ack` and `nack` functions for a ClojureScript project consuming this library.

Basically construct a `new StompFrame` with a command "ACK" or "NACK", call `frame.send(StompClient.stream)`

https://gist.github.com/gknapp/6c10695c8a8329f13378

**Comment by timgriffin** [comment]
@stephanMettler better late than never - here is an ack example.

https://gist.github.com/timgriffin/addaaaa612b3332381e58fa6eb571a69

**Comment by stephanMettler** [comment]
@timgriffin better late than never

Thanks for your example!
