### ISSUE TITLE
Cannot send larger messages using Stomp protocol

### ISSUE THREAD

**Issue by calvinKG** [easternbloc/node-stomp-client#27]
Cannot send larger messages using Stomp protocol (A large Json Message)

**Comment by easternbloc** [comment]
Could you give me a test case please?

**Comment by calvinKG** [comment]
We managed to fix this problem: 

Taken the source code from https://github.com/jmesnil/stomp-websocket/blob/master/lib/stomp.js and pasted into the local stomp.js lib and this fixes the issue.
