### ISSUE TITLE
Header parsing error with reply-to temporary queue from ActiveMQ

### ISSUE THREAD

**Issue by kgoerlitz** [easternbloc/node-stomp-client#29]
When a temporary queue is passed from ActiveMQ in the reply-to header, it contains embedded colons (':') like "/remote-temp-queue/ID:SYSTEM-NAME-49739-1421170578125-2:10:1".  The parser does not handle this properly.  It ends up stopping at the first embedded ':' and dropping the rest of the value, so the reply-to header ends up only containing "/remote-temp-queue/ID".

**Comment by easternbloc** [comment]
Fixed by #30
