### ISSUE TITLE
Topic Problem

### ISSUE THREAD

**Issue by caltras** [easternbloc/node-stomp-client#35]
Hi, 
It works with Topic?
I'm trying to connect to topic (jboss hornetq) but show a error
"{ '0': [Error: Error creating subscription subscription/jms.topic.bcssSaidaMonitoramento],  '1': 'HQ119032: User: bcssjmsuser doesnt have permission=CREATE_NON_DURABLE_QU
EUE on address {2}' }".
There is any special configuration to topic?

When I try Queue, it works. (jms.queue.bcssSaidaMonitoramento)

Thank you

**Comment by easternbloc** [comment]
Hi,

I'm afraid I've never used the client with hornetq so I can't offer much help. I can confirm there is no special configuration though so I'm guessing the permission problem is from the jboss side.

I'm going to close this but please re-open it if you find it's a problem with the client.

Thanks.
