### ISSUE TITLE
Documentation @ https://www.npmjs.com/package/stomp-client#stompaddress-port-user-pass-protocolversion-reconnectopts is slightly wrong

### ISSUE THREAD

**Issue by ArunMonySpin** [easternbloc/node-stomp-client#40]
The documentation https://www.npmjs.com/package/stomp-client#stompaddress-port-user-pass-protocolversion-reconnectopts 

mentions the "reconnectOptions" as the 6th argument, but in real its the 7th argument.  I had to go thru the code to figure out this discrepancy as no obvious errors are thrown when this is offered as the 6th argument. kindly correct the documentation.

**Comment by Slijkhuis** [comment]
+1 this was quite confusing to me too. The sixth argument is 'vhost', which has a default of `null`.

**Comment by easternbloc** [comment]
Fixed in #44
