### ISSUE TITLE
Cannot see reconnect event

### ISSUE THREAD

**Issue by dev0x10** [easternbloc/node-stomp-client#43]
I'm testing reconnection capability but I couldn't see the reconnection after I restart my ActiveMQ server.
Here is my code:
```javascript
var activemqClient = new Stomp(
  Config.get('ActiveMQ.host'), Config.get('ActiveMQ.port'),
  Config.get('ActiveMQ.username'), Config.get('ActiveMQ.password'),
  '1.0', null, {'retries':10, 'delay':3}
);

activemqClient.on('reconnect', function () {
  logger.info('ActiveMQ reconnected successfully');
});
```

On the documentation, Stomp parameters missing virtualHost as I see inside client.js.
```javascript
function StompClient(address, port, user, pass, protocolVersion, vhost, reconnectOpts) {...}
```

**Comment by easternbloc** [comment]
@dev0x10 I'm afraid I don't have time to look into this right now. If you get that time and want to issue a PR I'm more than happy to take a look.

Cheers.

**Comment by dev0x10** [comment]
@easternbloc okay i will take a look and issue a PR if necessary. Thanks!
